version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init.sql file
    networks:
      - discord_bot_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord_app
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"
    networks:
      - discord_bot_network
    depends_on:
      - mysql

networks:
  discord_bot_network:

volumes:
  db_data:
